version: '2'

networks:
 puppet:
  driver: bridge
  
volumes:
  puppetdb-certs-dir: {}
  
services:
  puppetdb-postgres:
    container_name: postgres
    networks:
      - puppet
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
    ports:
      - 5432:5432
    volumes:
      - ./initdb/:/docker-entrypoint-initdb.d

  puppetdb:
    hostname: puppetdb
    image: puppet/puppetdb:7.10.0
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - puppet
    environment:
      - USE_PUPPETSERVER=false
      - CONSUL_ENABLED=false
      - PUPPETDB_NODE_TTL=0s
    volumes:
      - "puppetdb-certs-dir:/opt/puppetlabs/server/data/puppetdb/certs"
